### ISSUE TITLE
Update to docker-outside-of-docker?

### ISSUE THREAD

**Issue by joebowbeer** [Go2Engle/tilt-in-devcontainer#1]
Has docker-outside-of-docker superceded docker-from-docker?

https://code.visualstudio.com/remote/advancedcontainers/use-docker-kubernetes

ghcr.io/devcontainers/features/docker-outside-of-docker:1

**Comment by Go2Engle** [comment]
I'll be honest it's been a long time since I have used this. I no longer use tilt.

**Comment by joebowbeer** [comment]
Time for another blog post - about what you do use? 😄

**Comment by joebowbeer** [comment]
Time for another blog post - about what you do use? 😄

**Comment by Go2Engle** [comment]
Haha I can if you'd like! It consists of using coder remote envs mixed with devbox.
